syntax = "All"
column_width = 100
indent_width = 4
indent_type = "Spaces"
line_endings = "Unix"
quote_style = "AutoPreferDouble"
call_parentheses = "Always"
collapse_simple_statement = "Never"
space_after_function_names = "Never"

[sort_requires]
enabled = false
